language: node_js

branches:
  only:
    - master
    - develop

cache:
  directories:
    - ~/.npm
    - ~/.cache

notifications:
  email: false

node_js:
- node

install:
  - npm ci

script: 
- npm run build
- npm test