# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
skip_tags: true

branches:
  only:
    - master
    - develop
    
cache:
  - '%AppData%\npm-cache -> appveyor.yml'
  - '%AppData%\..\Local\Cypress\Cache -> package-lock.json'

install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

test_script:
  - npm run test
